server:
  port: 8060

#http://localhost:8060/zuul-dev.yml
spring:
  application:
    name: microservice-config-server
  profiles:
    active: dev
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/408770558/spring-cloud-config
          username:
          password:
          #Spring Cloud \u914D\u7F6E\u5728 Git\u4E2D\u67E5\u627E\u914D\u7F6E\u6587\u4EF6\u662F\u90A3\u4E2A\u8DEF\u5F84 '{application}'    searchPaths: /config/**
          searchPaths: testConfig,zuulConfig,microserviceConfig
          default-label: master
          #\u6307\u5B9A\u4E00\u4E2A\u4E0D\u4F1A\u88AB\u5B9A\u671F\u6E05\u7406\u7684\u76EE\u5F55
          basedir: config-repo/config-repo
            #\u5982\u679C\u67D0\u79CD\u65B9\u5F0F\u672C\u5730\u526F\u672C\u53D8\u810F\uFF08\u4F8B\u5982\uFF0C\u7531\u64CD\u4F5C\u7CFB\u7EDF\u8FDB\u7A0B\u66F4\u6539\u6587\u4EF6\u5939\u5185\u5BB9\uFF09\uFF0C\u5219Spring Cloud Config\u670D\u52A1\u5668\u65E0\u6CD5\u4ECE\u8FDC\u7A0B\u5B58\u50A8\u5E93\u66F4\u65B0\u672C\u5730\u526F\u672C
          force-pull: true

eureka:
  client:
    #\u9ED8\u8BA4\u60C5\u51B5\u4E0B\u6CE8\u518C\u5230eureka server\u7684\u670D\u52A1\u662F\u901A\u8FC7\u5FC3\u8DF3\u6765\u544A\u77E5\u81EA\u5DF1\u662FUP\u8FD8\u662FDOWN\uFF0C\u5E76\u4E0D\u662F\u901A\u8FC7spring-boot-actuator\u6A21\u5757\u7684/health\u7AEF\u70B9\u6765\u5B9E\u73B0\u7684
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka-user.name}:${eureka-user.password}@${eureka-user.hostname}:${eureka-user.port}/eureka
  instance:
    #ip\u663E\u793A
    prefer-ip-address: true
    #\u81EA\u5B9A\u4E49\u663E\u793A
    instance-id: ${spring.application.name}:${server.port}

eureka-user:
  hostname: localhost
  port: 8761
  name: admin
  password: admin123
