spring:
  application:
    name: microservice-consumer-movie
server:
  port: 8081

eureka:
  client:
    #默认情况下注册到eureka server的服务是通过心跳来告知自己是UP还是DOWN，并不是通过spring-boot-actuator模块的/health端点来实现的
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka-user.name}:${eureka-user.password}@${eureka-user.hostname}:${eureka-user.port}/eureka
  instance:
    #ip显示
    prefer-ip-address: true
    #自定义显示
    instance-id: ${spring.application.name}:${server.port}

# 设置ribbon规则   api里的user 替换为applicationName
microservice-consumer-user:
  ribbon:
    # 设置为随机规则
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

eureka-user:
  hostname: localhost
  port: 8761
  name: admin
  password: admin123
