spring:
  application:
    name: microservice-consumer-movie-feign-hystrix
server:
  port: 8085

feign:
  hystrix:
    enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka-user.name}:${eureka-user.password}@${eureka-user.hostname}:${eureka-user.port}/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

#feign:
#  httpclient:
#    enabled: true

eureka-user:
  hostname: localhost
  port: 8761
  name: admin
  password: admin123

management:
  endpoints:
    web:
      exposure:
        include: '*'   #\u5141\u8BB8\u663E\u793A\u6240\u6709\u4FE1\u606F\uFF0C\u5305\u62EC/actuator/health\uFF0C/actuator/hystrix.stream

