-- drop table user;
-- create table user(
--      -- id bigint generated by as identity,
--     id bigint NOT NULL auto_increment,
--     username varchar(32),
--     name varchar(20),
--     age int(3),
--     balance decimal(10, 2),
--     primary key(id)
-- );

drop table user if exists;
create table user(
                     id bigint generated by default as identity,
                     username varchar(40),
                     name varchar(20),
                     age int(3),
                     balance decimal(10,2),
                     primary key(id)
);
