spring:
  application:
    name: microservice-consumer-movie-feign-customizing
server:
  port: 8083

eureka:
  client:
    #\u9ED8\u8BA4\u60C5\u51B5\u4E0B\u6CE8\u518C\u5230eureka server\u7684\u670D\u52A1\u662F\u901A\u8FC7\u5FC3\u8DF3\u6765\u544A\u77E5\u81EA\u5DF1\u662FUP\u8FD8\u662FDOWN\uFF0C\u5E76\u4E0D\u662F\u901A\u8FC7spring-boot-actuator\u6A21\u5757\u7684/health\u7AEF\u70B9\u6765\u5B9E\u73B0\u7684
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka-user.name}:${eureka-user.password}@${eureka-user.hostname}:${eureka-user.port}/eureka
  instance:
    #ip\u663E\u793A
    prefer-ip-address: true
    #\u81EA\u5B9A\u4E49\u663E\u793A
    instance-id: ${spring.application.name}:${server.port}

#feign:
#  httpclient:
#    enabled: true

eureka-user:
  hostname: localhost
  port: 8761
  name: admin
  password: admin123
