spring:
  application:
    name: microservice-consumer-movie-feign-customizing-without-hystrix
server:
  port: 8086

feign:
  hystrix:
    enabled: true

#\u8BBE\u7F6E\u5168\u5C40\u7684\u8D85\u65F6\u65F6\u95F4
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka-user.name}:${eureka-user.password}@${eureka-user.hostname}:${eureka-user.port}/eureka
  instance:
    #ip\u663E\u793A
    prefer-ip-address: true
    #\u81EA\u5B9A\u4E49\u663E\u793A
    instance-id: ${spring.application.name}:${server.port}

#feign:
#  httpclient:
#    enabled: true

eureka-user:
  hostname: localhost
  port: 8761
  name: admin
  password: admin123
